### ISSUE TITLE
Broken links in https://github.com/sourcemint/sm/blob/master/README.md

### ISSUE THREAD

**Issue by anaran** [sourcemint/sm#1]
Hi, these two give me 404:

https://github.com/sourcemint/docs/CommandLine.md

https://github.com/sourcemint/docs/PackageDescriptor.md

**Comment by cadorn** [comment]
Thanks!

FYI, This repo is a work in progress (not all dependencies are published yet). It will hold a refactored `sm` (npm install sm) which I hope to release publicly with website and docs later this month.
